# Generated by Django 4.2.7 on 2023-12-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("details", models.TextField()),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=50)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("0", "Planned"),
                            ("1", "Calcelled"),
                            ("2", "Postponed"),
                        ],
                        default="0",
                    ),
                ),
            ],
        ),
    ]
