# Generated by Django 4.2.7 on 2023-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[("0", "Planned"), ("1", "Cancelled"), ("2", "Postponed")],
                default="0",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
