# Generated by Django 4.2.7 on 2024-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_date_alter_event_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("0", "Planned"),
                    ("1", "Cancelled"),
                    ("2", "Postponed"),
                    ("3", "No date yet"),
                ],
                default="0",
            ),
        ),
    ]
