# Generated by Django 4.2.7 on 2024-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_rename_date_event_start_date_alter_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
