# Generated by Django 5.1.2 on 2024-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Planned"),
                    (1, "Cancelled"),
                    (2, "Postponed"),
                    (3, "No date yet"),
                ],
                default=0,
            ),
        ),
    ]
