# Generated by Django 5.1.2 on 2026-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Planned'), (1, 'Cancelled'), (2, 'Postponed')], default=0),
        ),
    ]
