# Generated by Django 4.0.4 on 2022-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sunday Service', max_length=50)),
                ('date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
