# Generated by Django 4.0.4 on 2022-04-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0001_initial'),
        ('morphers', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=5)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='stats.day')),
                ('facilitators', models.ManyToManyField(related_name='services_led', to='facilitators.facilitator')),
                ('morphers', models.ManyToManyField(related_name='services_attended', to='morphers.morpher')),
            ],
        ),
    ]
