# Generated by Django 4.0.4 on 2022-04-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_group_service_delete_servicestat_group_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(blank=True, default='Sunday Service', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='stats.day'),
        ),
    ]
