# Generated by Django 4.0.4 on 2022-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphers', '0003_alter_morpher_contact_alter_morpher_parents_contact'),
        ('stats', '0004_alter_day_comments_alter_day_date_alter_day_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='salvations',
            field=models.ManyToManyField(blank=True, null=True, to='morphers.morpher'),
        ),
        migrations.AddField(
            model_name='service',
            name='first_time_visitors',
            field=models.ManyToManyField(blank=True, null=True, to='morphers.morpher'),
        ),
    ]
