# Generated by Django 4.0.4 on 2022-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0002_alter_facilitator_contact'),
        ('stats', '0005_group_salvations_service_first_time_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='facilitators',
            field=models.ManyToManyField(related_name='days', to='facilitators.facilitator'),
        ),
        migrations.AlterField(
            model_name='group',
            name='facilitators',
            field=models.ManyToManyField(to='facilitators.facilitator'),
        ),
    ]
