# Generated by Django 4.0.4 on 2022-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphers', '0003_alter_morpher_contact_alter_morpher_parents_contact'),
        ('stats', '0006_day_facilitators_alter_group_facilitators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='salvations',
            field=models.ManyToManyField(blank=True, to='morphers.morpher'),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_time_visitors',
            field=models.ManyToManyField(blank=True, to='morphers.morpher'),
        ),
    ]
