# Generated by Django 4.0.4 on 2022-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
