# Generated by Django 4.2.2 on 2023-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0002_facilitator_in_band_facilitator_teaches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitator',
            old_name='in_band',
            new_name='only_in_band',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='teaches',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
