# Generated by Django 5.1.2 on 2026-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0004_tag_facilitator_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
