# Generated by Django 4.0.4 on 2022-04-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphers', '0002_school_morpher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpher',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='morpher',
            name='parents_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
