# Generated by Django 4.0.4 on 2022-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphers', '0003_alter_morpher_contact_alter_morpher_parents_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
