# Generated by Django 4.0.4 on 2023-04-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Sunday Celebration Services', max_length=50)),
                ('date', models.DateField(unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=20)),
                ('first_time_visitors', models.PositiveSmallIntegerField(default=0)),
                ('salvations', models.PositiveSmallIntegerField(default=0)),
                ('facilitators', models.PositiveSmallIntegerField(default=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Stat.stat')),
            ],
        ),
    ]
