# Generated by Django 4.0.4 on 2023-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0003_alter_service_junior_alter_service_senior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='date',
            new_name='stat',
        ),
    ]
