# Generated by Django 4.1.3 on 2023-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0004_rename_date_service_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facilitators',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_time_visitors',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='junior',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='salvations',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='senior',
            field=models.SmallIntegerField(),
        ),
    ]
