# Generated by Django 4.1.3 on 2023-05-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0005_alter_service_facilitators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facilitators',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_time_visitors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='junior',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='salvations',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='senior',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
