# Generated by Django 5.1.2 on 2024-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stat", "0007_service_facilitators_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="non_system_facilitators",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
