# Generated by Django 5.1.4 on 2026-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0008_service_non_system_facilitators'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fixed_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
