# Generated by Django 5.1.4 on 2026-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stat', '0009_service_fixed_total'),
        ('facilitators', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facilitators_available',
            field=models.ManyToManyField(blank=True, related_name='services_served', to='facilitators.facilitator'),
        ),
    ]
